# -*- coding: utf-8 -*-
"""Streamlit_APP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11AFbzDz7AkHrIYtEXBFQ37ulVERxregT
"""

!pip install streamlit

import streamlit as st
import pandas as pd
# Import other libraries for your SQL query generator and dataframe operations

import streamlit as st

def main():
    st.title("My First Streamlit App")
    st.write("Welcome to Streamlit!")
    st.write("This is a basic example.")

if __name__ == "__main__":
    main()

streamlit run Streamlit_APP.py